# Generated by Django 3.1.1 on 2020-10-01 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20201001_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(blank=True, default='', related_name='tasks', to='tasks.Tag'),
        ),
    ]
